:<<"::CMDLITERAL"
@echo off
REM ===== WINDOWS branch (double-click, or: ONBOARD-ANYWHERE.cmd) =====
where powershell >nul 2>&1 || ( echo PowerShell not found. & pause & goto :eof )
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAQQBJAFgATQBPAFMAIABPAFAARQBSAEEAVABPAFIAIABTAFQAQQBUAEkATwBOACAALQAgAFAAbwB3AGUAcgBlAGQAIABiAHkAIABQAFIATwBKAEUAQwBUACAAWAAgAEEASQBYAE0ATwBTACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAQwB5AGEAbgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwBXAEgAQQBUACAAVABIAEkAUwAgAEQATwBFAFMAOgAgAGkAbgBzAHQAYQBsAGwAcwAgAHQAaABlACAAbwBwAGUAcgBhAHQAbwByACAAdABvAG8AbABrAGkAdAAgAHQAbwAgAH4ALwBBAEkAWABNAE8AUwAtAE8AUABFAFIAQQBUAE8AUgAsACAAcgBlAGcAaQBzAHQAZQByAHMAIAB5AG8AdQAgAGEAcwAgAGEAIABGAEUATgBDAEUARAAgAG8AcABlAHIAYQB0AG8AcgAgACgAdABoAGUAIABvAHcAbgBlAHIAIABoAG8AbABkAHMAIAB0AGgAZQAgAGsAZQB5AHMAIABhAG4AZAAgAGwAaQBjAGUAbgBzAGkAbgBnACkALAAgAGEAbgBkACAAcAByAGUAcABhAHIAZQBzACAAdABoAGkAcwAgAFAAQwAgAHQAbwAgAGoAbwBpAG4AIABQAFIATwBKAEUAQwBUACAAWAAgAEEASQBYAE0ATwBTACAAbgBlAHQAdwBvAHIAawAgACgAdABoAGUAIABvAHcAbgBlAHIAIABhAHAAcAByAG8AdgBlAHMAIAB5AG8AdQByACAAZABlAHYAaQBjAGUAKQAuACAATgBvACAAcABhAHMAcwB3AG8AcgBkAHMAIAB0AGEAawBlAG4ALgAgAE4AbwB0AGgAaQBuAGcAIABoAGkAZABkAGUAbgAuACcACgAkAGMAIAA9ACAAUgBlAGEAZAAtAEgAbwBzAHQAIAAnAFQAeQBwAGUAIAAgAEkAIABKAE8ASQBOACAAVABIAEUAIABOAEUAVABXAE8AUgBLACAAIAB0AG8AIABjAG8AbgB0AGkAbgB1AGUAJwAKAGkAZgAgACgAJABjAC4AVAByAGkAbQAoACkALgBUAG8AVQBwAHAAZQByACgAKQAgAC0AbgBlACAAJwBJACAASgBPAEkATgAgAFQASABFACAATgBFAFQAVwBPAFIASwAnACkAewAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnAEMAYQBuAGMAZQBsAGwAZQBkAC4AIABOAG8AdABoAGkAbgBnACAAYwBoAGEAbgBnAGUAZAAuACcAOwAgAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgADIAOwAgAGUAeABpAHQAIAB9AAoAJABuAGEAbQBlACAAPQAgAFIAZQBhAGQALQBIAG8AcwB0ACAAJwBGAGkAcgBzAHQAIABuAGEAbQBlACcAOwAgACQAZQBtAGEAaQBsACAAPQAgAFIAZQBhAGQALQBIAG8AcwB0ACAAJwBFAG0AYQBpAGwAJwAKAGkAZgAoAC0AbgBvAHQAIAAoAEcAZQB0AC0AQwBvAG0AbQBhAG4AZAAgAGcAaQB0ACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlACkAKQB7ACAAVwByAGkAdABlAC0ASABvAHMAdAAgACcASQBuAHMAdABhAGwAbABpAG4AZwAgAEcAaQB0ACAAKABvAG4AZQAtAHQAaQBtAGUAKQAuAC4ALgAnADsAIAB3AGkAbgBnAGUAdAAgAGkAbgBzAHQAYQBsAGwAIAAtAC0AaQBkACAARwBpAHQALgBHAGkAdAAgAC0AZQAgAC0ALQBzAGkAbABlAG4AdAAgAC0ALQBhAGMAYwBlAHAAdAAtAHAAYQBjAGsAYQBnAGUALQBhAGcAcgBlAGUAbQBlAG4AdABzACAALQAtAGEAYwBjAGUAcAB0AC0AcwBvAHUAcgBjAGUALQBhAGcAcgBlAGUAbQBlAG4AdABzACAAfQAKACQAZABpAHIAIAA9ACAASgBvAGkAbgAtAFAAYQB0AGgAIAAkAEgATwBNAEUAIAAnAEEASQBYAE0ATwBTAC0ATwBQAEUAUgBBAFQATwBSACcACgBnAGkAdAAgAGMAbABvAG4AZQAgAC0ALQBkAGUAcAB0AGgAIAAxACAAaAB0AHQAcABzADoALwAvAGcAaQB0AGgAdQBiAC4AYwBvAG0ALwBBAEkAWABNAE8AUwA1ADMANwAvAFQATQBNAFQALgBnAGkAdAAgACIAJABkAGkAcgAiACAAMgA+ACQAbgB1AGwAbAAKAE4AZQB3AC0ASQB0AGUAbQAgAC0ASQB0AGUAbQBUAHkAcABlACAARABpAHIAZQBjAHQAbwByAHkAIAAtAEYAbwByAGMAZQAgAC0AUABhAHQAaAAgACgASgBvAGkAbgAtAFAAYQB0AGgAIAAkAGQAaQByACAAJwAuAHMAdwBhAHIAbQAnACkAIAB8ACAATwB1AHQALQBOAHUAbABsAAoAJwBvAHAAZQByAGEAdABvAHIAJwAgAHwAIABTAGUAdAAtAEMAbwBuAHQAZQBuAHQAIAAoAEoAbwBpAG4ALQBQAGEAdABoACAAJABkAGkAcgAgACcALgBzAHcAYQByAG0AXAByAG8AbABlACcAKQAKACIAbwBwAGUAcgBhAHQAbwByAC0AJABuAGEAbQBlACIAIAB8ACAAUwBlAHQALQBDAG8AbgB0AGUAbgB0ACAAKABKAG8AaQBuAC0AUABhAHQAaAAgACQAZABpAHIAIAAnAC4AcwB3AGEAcgBtAFwAbQBhAGMAaABpAG4AZQAnACkACgAkAHAAcgBvAGYAIAA9ACAASgBvAGkAbgAtAFAAYQB0AGgAIAAoAFsARQBuAHYAaQByAG8AbgBtAGUAbgB0AF0AOgA6AEcAZQB0AEYAbwBsAGQAZQByAFAAYQB0AGgAKAAnAEQAZQBzAGsAdABvAHAAJwApACkAIAAiAEEASQBYAE0ATwBTAC0AbwBwAGUAcgBhAHQAbwByAC0AJABuAGEAbQBlAC4AdAB4AHQAIgAKACIAQQBJAFgATQBPAFMAIABPAFAARQBSAEEAVABPAFIAIABQAFIATwBGAEkATABFAGAAcgBgAG4AbgBhAG0AZQA6ACAAJABuAGEAbQBlAGAAcgBgAG4AZQBtAGEAaQBsADoAIAAkAGUAbQBhAGkAbABgAHIAYABuAG0AYQBjAGgAaQBuAGUAOgAgACQAZQBuAHYAOgBDAE8ATQBQAFUAVABFAFIATgBBAE0ARQBgAHIAYABuAHIAbwBsAGUAOgAgAG8AcABlAHIAYQB0AG8AcgAgACgAZgBlAG4AYwBlAGQAKQBgAHIAYABuAHMAdABhAHQAdQBzADoAIABBAFcAQQBJAFQASQBOAEcAIABPAFcATgBFAFIAIABBAEMAVABJAFYAQQBUAEkATwBOACIAIAB8ACAAUwBlAHQALQBDAG8AbgB0AGUAbgB0ACAAJABwAHIAbwBmAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnAE8AUABFAFIAQQBUAE8AUgAgAFMAVABBAFQASQBPAE4AIABSAEUAQQBEAFkAIAAoAHAAZQBuAGQAaQBuAGcAIABhAGMAdABpAHYAYQB0AGkAbwBuACkAJwAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAxACkAIABTAGUAbgBkACAAJABwAHIAbwBmACAAYgBhAGMAawAgAHQAbwAgAHQAaABlACAAbwB3AG4AZQByAC4AIgAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnADIAKQAgAE8AdwBuAGUAcgAgAGEAcABwAHIAbwB2AGUAcwAgAHkAbwB1AHIAIABkAGUAdgBpAGMAZQAgACsAIABhAGMAdABpAHYAYQB0AGUAcwAgAHkAbwB1AHIAIABsAGkAYwBlAG4AcwBlAC4AJwAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnADMAKQAgAEkAbgBzAHQAYQBsAGwAIABUAGEAaQBsAHMAYwBhAGwAZQA6ACAAaAB0AHQAcABzADoALwAvAHQAYQBpAGwAcwBjAGEAbABlAC4AYwBvAG0ALwBkAG8AdwBuAGwAbwBhAGQAJwAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnADQAKQAgAFUAcwBlACAARwBpAHQAIABCAGEAcwBoACAAZgBvAHIAIAB0AGgAZQAgAG8AbgBlAC0AdwBvAHIAZAAgAGMAbwBtAG0AYQBuAGQAcwAgAGEAZgB0AGUAcgAgAGEAYwB0AGkAdgBhAHQAaQBvAG4ALgAnAAoAUgBlAGEAZAAtAEgAbwBzAHQAIAAnAFAAcgBlAHMAcwAgAEUATgBUAEUAUgAgAHQAbwAgAGMAbABvAHMAZQAnAAoA
goto :eof
::CMDLITERAL
# ===== UNIX branch (macOS / Linux):  bash ONBOARD-ANYWHERE.cmd =====
set -uo pipefail
REPO_URL="${AIXMOS_REPO:-https://github.com/AIXMOS537/TMMT.git}"
INSTALL_DIR="$HOME/AIXMOS-OPERATOR"; PHRASE="I JOIN THE NETWORK"
G=$'\e[32m'; CY=$'\e[36m'; BD=$'\e[1m'; D=$'\e[2m'; X=$'\e[0m'
clear 2>/dev/null || true
printf '%s\n' "${CY}${BD}AIXMOS OPERATOR STATION — Powered by PROJECT X AIXMOS${X}"
cat <<'M'

  WHAT THIS DOES: installs the operator toolkit to ~/AIXMOS-OPERATOR, registers you
  as a FENCED operator (the owner holds the keys + licensing), and prepares this
  machine to join PROJECT X AIXMOS's network (the owner approves your device).
  No passwords taken. Nothing hidden. You can stop now.
M
printf '\n  Type  %s%s%s  to continue: ' "$BD" "$PHRASE" "$X"
IFS= read -r r
[ "$(printf '%s' "$r" | tr '[:lower:]' '[:upper:]' | xargs)" = "$PHRASE" ] || { printf '\n  Cancelled. Nothing changed.\n\n'; exit 0; }
read -p "  First name: " NM; read -p "  Email: " EM
command -v git >/dev/null 2>&1 || { echo "  git required — install it then re-run"; exit 1; }
if [ -d "$INSTALL_DIR/.git" ]; then ( cd "$INSTALL_DIR" && git pull --rebase --quiet 2>/dev/null ); else git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" >/dev/null 2>&1 || { echo "  clone failed"; exit 1; }; fi
cd "$INSTALL_DIR"; mkdir -p .swarm; echo operator > .swarm/role; echo "operator-$(printf '%s' "${NM:-op}" | tr '[:upper:] ' '[:lower:]-')" > .swarm/machine
git config core.hooksPath scripts/hooks 2>/dev/null || true
install_words(){ local rc="$1" t; t="$(mktemp)"; [ -e "$rc" ] && grep -v 'AIXMOS_WORDS' "$rc" 2>/dev/null > "$t" || true
  { echo "# AIXMOS_WORDS"; for w in menu compass watchtower; do echo "alias $w='bash \"$INSTALL_DIR/scripts/$w\"'  # AIXMOS_WORDS"; done
    echo "alias dark='bash \"$INSTALL_DIR/scripts/godark\"'    # AIXMOS_WORDS"
    echo "alias work='bash \"$INSTALL_DIR/scripts/tmmt\" go 2' # AIXMOS_WORDS"
    echo "alias sync='bash \"$INSTALL_DIR/scripts/tmmt\" sync' # AIXMOS_WORDS"
    echo "alias sos='bash \"$INSTALL_DIR/scripts/tmmt\" help'  # AIXMOS_WORDS"; } >> "$t"; mv "$t" "$rc"; }
touch ~/.zshrc ~/.bashrc 2>/dev/null || true; for rc in ~/.zshrc ~/.bashrc; do install_words "$rc"; done
PROF="$HOME/Desktop/AIXMOS-operator-${NM:-op}.txt"; [ -d "$HOME/Desktop" ] || PROF="$HOME/AIXMOS-operator-${NM:-op}.txt"
{ echo "AIXMOS OPERATOR PROFILE"; echo "name: ${NM:-}"; echo "email: ${EM:-}"; echo "machine: $(hostname 2>/dev/null)"; echo "role: operator (fenced)"; echo "status: AWAITING OWNER ACTIVATION"; } > "$PROF"
printf '\n%s  OPERATOR STATION READY (pending activation)%s\n' "$G$BD" "$X"
printf '   1) Send %s back to the owner.\n   2) Owner approves your device + activates your license.\n   3) Install Tailscale: https://tailscale.com/download\n' "$PROF"
printf '   4) Open a new terminal and type: %smenu%s\n\n' "$BD" "$X"
printf '%s   Fenced operator on PROJECT X AIXMOS. Owner holds the keys.%s\n\n' "$D" "$X"
exit 0
