#!/usr/bin/env python3
"""VA Liberation Phase 1 — nightly lead triage → morning call sheet.

Machines sort. Humans talk. Pulls actionable leads from Airtable (Incoming
Leads + Waitlist), applies the canonical do-not-contact list, dedupes by
phone, and renders one call sheet into the vault. DRAFT-ONLY: this script
never sends anything, never writes to Airtable, never touches ClickUp.

Credentials: ~/.config/tmmt/airtable.env (mode 600) containing one line
whose name is AIRTABLE_PAT (or AIRTABLE_API_KEY) set to your token.
If the key file is missing, the sheet is still written with a NEEDS-KEY
banner so the gap is visible in 02-Needs-You instead of failing silently
(the Jan-15 lesson: silence hides breakage).
"""

import json
import os
import re
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

BASE = "appcenWUju039rD7b"
LEADS_TABLE = "tbl4gndUYeiOUWYRR"      # "Incoming Leads"
WAITLIST_TABLE = "tblaYxS00uU1dBNGX"   # "Waitlist"
VAULT = Path.home() / "Brain/vault"
DNC_FILE = VAULT / "03-Systems/do-not-contact.md"
OUT_DIR = VAULT / "02-Needs-You"
ENV_FILE = Path.home() / ".config/tmmt/airtable.env"

# Lead statuses worth a human's time. Everything else (Closed, DND,
# Duplicate, Active customer, Converted, Not Interested) is excluded.
LEAD_STATUSES = {"New Lead", "Qualified", "Follow-Up"}
WAITLIST_STATUSES = {"Waiting", "Reach out later", "keep updated on new availability"}


def load_key():
    if not ENV_FILE.exists():
        return None
    for line in ENV_FILE.read_text().splitlines():
        name, sep, value = line.partition("=")
        if sep and name.strip() in ("AIRTABLE_PAT", "AIRTABLE_API_KEY"):
            return value.strip()
    return None


def normalize_phone(raw):
    if not raw:
        return None
    digits = re.sub(r"\D", "", str(raw))
    if len(digits) == 10:
        digits = "1" + digits
    return "+" + digits if len(digits) == 11 else None


def load_dnc():
    """Every +1XXXXXXXXXX in the DNC file is excluded, hard or soft."""
    if not DNC_FILE.exists():
        return set()
    return set(re.findall(r"\+1\d{10}", DNC_FILE.read_text()))


def fetch_all(key, table):
    records, offset = [], None
    while True:
        url = f"https://api.airtable.com/v0/{BASE}/{table}?pageSize=100"
        if offset:
            url += f"&offset={offset}"
        req = urllib.request.Request(url, headers={"Authorization": f"Bearer {key}"})
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
        records.extend(data.get("records", []))
        offset = data.get("offset")
        if not offset:
            return records


def bucket(created_iso, now):
    try:
        created = datetime.fromisoformat(created_iso.replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return "UNKNOWN"
    days = (now - created).days
    if days <= 7:
        return "HOT"
    if days <= 30:
        return "WARM"
    if days <= 90:
        return "STALE"
    return "OLD"


def main():
    now = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d")
    out = OUT_DIR / f"CALL-SHEET-{today}.md"
    dnc = load_dnc()
    key = load_key()

    lines = [
        f"# CALL SHEET — {today}",
        "*Generated by va-liberation/triage_leads.py. Draft-only: nothing was sent.*",
        "",
        "**Rules:** call between 9:00–20:00 only · never state a balance not pulled",
        "from Stripe today · log outcome as one line next to the name",
        "(`PAID $x / PLAN <day> / GHOST / DISPUTE / BOOKED`) · anyone asking to be",
        "left alone goes on the DNC list same-day.",
        "",
    ]

    if not key:
        lines += [
            "> ⚠️ **NEEDS KEY** — `~/.config/tmmt/airtable.env` is missing or has no",
            "> AIRTABLE_PAT entry. This sheet could not pull live Airtable data.",
            "> Drop the key in (mode 600) and re-run, or ask Claude to generate",
            "> today's sheet via MCP.",
            "",
        ]
        out.write_text("\n".join(lines))
        print(f"wrote {out} (needs key)")
        return 0

    leads = fetch_all(key, LEADS_TABLE)
    waitlist = fetch_all(key, WAITLIST_TABLE)

    seen_phones, sections = set(), {"HOT": [], "WARM": [], "STALE": [], "OLD": []}
    excluded_dnc = excluded_junk = 0

    def add(name, phone, context, created, source):
        nonlocal excluded_dnc, excluded_junk
        p = normalize_phone(phone)
        if not p:
            excluded_junk += 1
            return
        if p in dnc:
            excluded_dnc += 1
            return
        if p in seen_phones:
            return
        seen_phones.add(p)
        b = bucket(created, now) if created else "OLD"
        sections.setdefault(b, sections["OLD"])
        sections[b if b in sections else "OLD"].append(
            f"- [ ] **{name or 'Unknown'}** — {p} · {source} · {context}"
        )

    for r in leads:
        f = r.get("fields", {})
        status = f.get("Status")
        status_name = status.get("name") if isinstance(status, dict) else status
        if status_name not in LEAD_STATUSES:
            continue
        add(
            f.get("Contact Name", "").strip(),
            f.get("SMS Number (auto)") or f.get("phone"),
            (f.get("Notes") or "").strip()[:90] or "no notes",
            f.get("Created on") or r.get("createdTime"),
            f"lead:{status_name}",
        )

    for r in waitlist:
        f = r.get("fields", {})
        status = f.get("Status")
        status_name = status.get("name") if isinstance(status, dict) else status
        if status_name not in WAITLIST_STATUSES:
            continue
        want = f.get("Vehicle Type")
        want_name = want.get("name") if isinstance(want, dict) else (want or "any vehicle")
        add(
            f.get("Customer Name", "").strip(),
            f.get("Customer Phone"),
            f"waitlist · wants {want_name}",
            f.get("Date Added to Waitlist") or r.get("createdTime"),
            f"waitlist:{status_name}",
        )

    titles = [
        ("HOT", "🔥 HOT — contacted us / entered ≤7 days (call first)"),
        ("WARM", "🟡 WARM — 8–30 days"),
        ("STALE", "🟠 STALE — 31–90 days (re-open soft: 'still looking?')"),
        ("OLD", "⚪ OLD — 90+ days, inventory-dependent (call only when a unit is free)"),
    ]
    for key_, title in titles:
        rows = sections[key_]
        lines += [f"## {title}", ""]
        lines += rows if rows else ["*(none)*"]
        lines += ["", f"*{len(rows)} contact(s)*", ""]

    lines += [
        "---",
        f"*Excluded: {excluded_dnc} DNC · {excluded_junk} no-phone/junk records ·",
        f"deduped to {len(seen_phones)} unique numbers. DNC source: {DNC_FILE}.*",
    ]
    out.write_text("\n".join(lines))
    print(f"wrote {out}: {len(seen_phones)} contacts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
