#!/usr/bin/env bash
# Phase 9 — interactive notification wiring.
# Prompts for each credential, writes .env.notify (mode 600), and runs the Vercel env+deploy script.
# Safe to re-run. Press Enter to skip any field — that channel just won't fire.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.notify"

read_secret() {
  local label="$1"
  local var
  printf '%s\n' "$label" >&2
  printf '  > ' >&2
  read -r var
  printf '%s' "${var}"
}

read_plain() {
  local label="$1"
  local var
  printf '%s\n' "$label" >&2
  printf '  > ' >&2
  read -r var
  printf '%s' "${var}"
}

echo "==> Phase 9 notification setup"
echo ""
echo "    Press Enter on any prompt to skip that channel."
echo "    Inputs are not echoed back to history."
echo ""

SLACK_WEBHOOK_URL_IN="$(read_secret 'Slack incoming-webhook URL  (starts with https://hooks.slack.com/services/...)')"
TELEGRAM_BOT_TOKEN_IN="$(read_secret 'Telegram bot token          (looks like 123456789:ABC-DEF...)')"
TELEGRAM_OWNER_CHAT_ID_IN="$(read_plain  'Telegram owner chat ID      (a number)')"

# Write env file with mode 600
umask 077
cat > "${ENV_FILE}" <<EOF
# Auto-generated by wire-it.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not commit. Gitignored.
SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL_IN}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN_IN}
TELEGRAM_OWNER_CHAT_ID=${TELEGRAM_OWNER_CHAT_ID_IN}
IMESSAGE_RELAY_URL=
IMESSAGE_NOTIFY_TO=
IMESSAGE_RELAY_TOKEN=
EOF
chmod 600 "${ENV_FILE}"

echo ""
echo "==> wrote ${ENV_FILE} (mode 600)"
echo ""

# Re-export into current shell so set-vercel-notify-env.sh sees them
set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

# Run the wire script
"${SCRIPT_DIR}/set-vercel-notify-env.sh"
