#!/usr/bin/env bash
# ============================================================================
# activate-m1-brain.sh — turn the M1 home brain ON, for real.
#
# Run this ON the M1 (brainiac-mac), from the repo root:
#     bash scripts/activate-m1-brain.sh            # activate
#     bash scripts/activate-m1-brain.sh --check    # dry-run: show the plan, touch nothing
#
# What it does, in order:
#   1) Lay down the Home Brain Safety Layer state (~/.aixmos: audit dir, env,
#      kill-switch path) and clear any stale HALT — you are explicitly activating.
#   2) PROVE the safety layer works on THIS machine (runs the guard test suite).
#      If the guard fails, it refuses to activate. No "it's okay" — it's checked.
#   3) Make sure Ollama + the router's models are present.
#   4) Install an always-on LaunchAgent for the LiteLLM router (survives reboot).
#   5) Print the phone kill switch.
#
# Idempotent + safe to re-run. --check makes no changes (runs anywhere).
# ============================================================================
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT" || exit 1

MODE="${1:-run}"
DRY=0; [ "$MODE" = "--check" ] && DRY=1

if [ -t 1 ]; then G=$'\e[32m'; R=$'\e[31m'; Y=$'\e[33m'; BD=$'\e[1m'; X=$'\e[0m'; else G=; R=; Y=; BD=; X=; fi
say(){ printf '%s\n' "$*"; }
ok(){   printf '%s✓%s %s\n' "$G" "$X" "$*"; }
warn(){ printf '%s!%s %s\n' "$Y" "$X" "$*" >&2; }
err(){  printf '%s✗%s %s\n' "$R" "$X" "$*" >&2; }
step(){ printf '\n%s== %s ==%s\n' "$BD" "$*" "$X"; }
banner(){ printf '\n%s%s%s\n' "$BD$G" "$*" "$X"; }
run(){ if [ "$DRY" = 1 ]; then say "   would: $*"; else eval "$*"; fi; }

AIXMOS_HOME="${AIXMOS_HOME:-$HOME/.aixmos}"
AUDIT_DIR="${AIXMOS_AUDIT_DIR:-$AIXMOS_HOME/audit}"
CAP="${AIXMOS_DAILY_CAP_USD:-10}"
KILL_FILE="$AIXMOS_HOME/HALT"

step "M1 Home Brain activation${DRY:+ (dry-run)}"
[ "$DRY" = 1 ] || [ "$(uname -s)" = "Darwin" ] || warn "not macOS — LaunchAgent step will be skipped (meant for the M1)"

# ---------------------------------------------------------------------------
step "1) Safety layer state + env"
run "mkdir -p '$AIXMOS_HOME' '$AUDIT_DIR'"
if [ -f "$KILL_FILE" ]; then
  warn "HALT sentinel present — clearing it (you are activating)"
  run "rm -f '$KILL_FILE'"
fi
ENV_FILE="$AIXMOS_HOME/brain.env"
if [ "$DRY" = 1 ]; then
  say "   would write env → $ENV_FILE (AIXMOS_HOME, AIXMOS_AUDIT_DIR, AIXMOS_DAILY_CAP_USD=$CAP, AIXMOS_KILL_FILE)"
else
  cat > "$ENV_FILE" <<EOF
# Home Brain Safety Layer — sourced by the app/agent loop. Generated by activate-m1-brain.sh
AIXMOS_HOME=$AIXMOS_HOME
AIXMOS_AUDIT_DIR=$AUDIT_DIR
AIXMOS_DAILY_CAP_USD=$CAP
AIXMOS_KILL_FILE=$KILL_FILE
EOF
  ok "env → $ENV_FILE"
fi

# ---------------------------------------------------------------------------
step "2) PROVE the guard works on this machine"
if command -v npm >/dev/null 2>&1 && [ -d node_modules ]; then
  if [ "$DRY" = 1 ]; then
    say "   would run: npm test -- shared/home-brain  (refuse to activate if it fails)"
  else
    say "→ running the Home Brain Safety Layer tests…"
    if npm test -- shared/home-brain >/dev/null 2>&1; then
      ok "kill switch · spend cap · PII firewall · owner gate · audit — all verified HERE"
    else
      err "guard tests FAILED on this machine — NOT activating. Fix first: npm test -- shared/home-brain"
      exit 1
    fi
  fi
else
  warn "npm or node_modules missing — run 'npm ci' first so the guard can be verified"
  [ "$DRY" = 1 ] || exit 1
fi

# ---------------------------------------------------------------------------
step "3) Ollama + router models"
if command -v ollama >/dev/null 2>&1; then
  for m in qwen2.5:14b qwen2.5-coder:14b; do
    if ollama list 2>/dev/null | grep -q "${m%%:*}"; then ok "model $m present"
    else warn "model $m missing"; run "ollama pull '$m'"; fi
  done
else
  warn "ollama not installed — get it at https://ollama.com/download, then re-run"
fi

# ---------------------------------------------------------------------------
step "4) Always-on router (LaunchAgent)"
PLIST="$HOME/Library/LaunchAgents/com.aixmos.brain-router.plist"
if [ "$(uname -s)" = "Darwin" ]; then
  if [ "$DRY" = 1 ]; then
    say "   would install + load $PLIST (RunAtLoad + KeepAlive → survives reboot)"
  else
    mkdir -p "$HOME/Library/LaunchAgents"
    cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.aixmos.brain-router</string>
  <key>ProgramArguments</key><array>
    <string>/bin/bash</string><string>$ROOT/scripts/brain-router.sh</string>
  </array>
  <key>EnvironmentVariables</key><dict>
    <key>AIXMOS_HOME</key><string>$AIXMOS_HOME</string>
    <key>AIXMOS_AUDIT_DIR</key><string>$AUDIT_DIR</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$AIXMOS_HOME/brain-router.log</string>
  <key>StandardErrorPath</key><string>$AIXMOS_HOME/brain-router.err.log</string>
</dict></plist>
EOF
    launchctl unload "$PLIST" 2>/dev/null || true
    if launchctl load "$PLIST" 2>/dev/null; then ok "router LaunchAgent loaded — always-on, restarts on boot"
    else warn "launchctl load failed — start manually: bash scripts/brain-router.sh"; fi
  fi
else
  warn "skipping LaunchAgent (not macOS) — this step activates on the M1"
fi

# ---------------------------------------------------------------------------
banner "BRAIN ${DRY:+WOULD BE }ACTIVE"
say "Router (tailnet-only):   http://<brain-tailnet-ip>:${BRAIN_ROUTER_PORT:-4000}/v1"
say "Kill switch (phone):     touch $KILL_FILE      # halts every guarded action"
say "Resume:                  rm $KILL_FILE"
say "Audit trail:             $AUDIT_DIR/home-brain-audit.jsonl"
[ "$DRY" = 1 ] && say "${Y}(dry-run — nothing was changed. Re-run without --check to activate.)${X}"
exit 0
