#!/usr/bin/env bash
# finance-sweep — bills due-soon + subscription cost hints (read-only)
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIN="$ROOT/imports/finance"
CSV="$FIN/master-bills.csv"
AUDIT="$FIN/subscriptions-audit.md"
TODAY="$(date +%Y-%m-%d)"
DAY="$(date +%-d 2>/dev/null || date +%d | sed 's/^0//')"

G=$'\e[32m'; Y=$'\e[33m'; R=$'\e[31m'; C=$'\e[36m'; B=$'\e[1m'; D=$'\e[2m'; X=$'\e[0m'

say() { printf '%s\n' "$*"; }

say ""
say "${B}${C}FINANCE SWEEP${X}  ($TODAY)"
say "${D}God → self → family → others · entity-separated books${X}"
say ""

# --- Bills CSV
if [[ ! -f "$CSV" ]]; then
  say "${R}Missing $CSV — copy from imports/finance/README.md${X}"
  exit 1
fi

TOTAL=0
DUE_SOON=0
say "${B}Bills register${X}"
while IFS= read -r line; do
  [[ "$line" == Bill\ Name* ]] && continue
  [[ -z "${line// /}" ]] && continue
  IFS=',' read -r name entity _owner _cat _vendor amount due_day _freq _auto _acct status _tier _decision _action _notes <<< "$line"
  amount="${amount// /}"
  due_day="${due_day// /}"
  [[ "$amount" =~ ^[0-9]+(\.[0-9]+)?$ ]] && TOTAL=$((TOTAL + ${amount%.*}))

  if [[ "$due_day" =~ ^[0-9]+$ ]]; then
    diff=$(( (due_day - DAY + 31) % 31 ))
    if [[ "$diff" -le 7 && "$status" != "Paid" ]]; then
      say "  ${Y}◆${X} Due ~${diff}d: ${name} (${entity}) \$${amount:-?} — day ${due_day}"
      DUE_SOON=$((DUE_SOON + 1))
    fi
  fi
done < "$CSV"

if [[ "$DUE_SOON" -eq 0 ]]; then
  say "  ${G}●${X} No unpaid bills flagged due within 7 days (check CSV amounts — many are placeholders)"
fi
say "  ${D}Tracked monthly (where amount filled): ~\$${TOTAL}/mo${X}"
say ""

# --- Known stack hints (from COST-AND-CAPACITY.md)
say "${B}Cost-cut checklist${X}"
say "  ${G}●${X} Retire Airtable if Supabase is source of truth"
say "  ${Y}○${X} Set Anthropic API monthly cap (console.anthropic.com)"
say "  ${Y}○${X} Vercel → Settings → Spend Management"
say "  ${Y}○${X} GHL tier audit — confirm plan matches usage"
say "  ${Y}○${X} ClickUp — remove seats for non-users"
say "  ${G}●${X} One Claude Max seat (Cursor + Claude Code) — don't duplicate dev AI"
say ""

# --- Vercel project count (if CLI works)
if command -v vercel >/dev/null 2>&1; then
  VC=$(vercel project ls --scope aixmos537 2>/dev/null | grep -c '\.vercel\.app' || echo "?")
  say "${B}Vercel${X}: ${VC} production apps on team aixmos537 (~\$20/mo Pro covers team)"
fi

# --- Write audit markdown
mkdir -p "$FIN"
{
  echo "# Subscriptions audit — $TODAY"
  echo ""
  echo "Generated by \`scripts/finance-sweep.sh\`. Edit \`master-bills.csv\` for truth."
  echo ""
  echo "## Due soon (7-day window)"
  echo "- Flagged: **$DUE_SOON** rows (see terminal output)"
  echo ""
  echo "## Monthly stack (documented targets)"
  echo "| Tool | Est. | Notes |"
  echo "|------|------|-------|"
  echo "| Vercel Pro | ~\$20 | 5 apps, one team |"
  echo "| Supabase | \$0–25 | Free until MAU/DB limit |"
  echo "| GHL | ~\$97–497 | **Confirm your tier** |"
  echo "| Claude Max (dev) | ~\$100–200 | Owner dev seat only |"
  echo "| ClickUp | ~\$7–12/seat | Staff only |"
  echo "| Airtable | retire? | Data in Supabase |"
  echo ""
  echo "## Entity reminder"
  echo "- Personal / Family / TMMT / AIXMOS / Moe Legacy — **separate accounts**"
  echo "- See \`docs/FINANCIAL-PRIORITY-LEDGER.md\`"
} > "$AUDIT"

say "${B}One step:${X} Fill real amounts in imports/finance/master-bills.csv (start with GHL + rent + Claude)"
say "${D}Audit written: $AUDIT${X}"
say ""

exit 0
