#!/usr/bin/env bash
# Rescue Dispatch + 3-app ecosystem smoke test.
#
# Run before a demo, after a deploy, or to verify state is consistent.
# No external dependencies beyond curl and a checked-out master.
#
# Exits non-zero if any check fails. Prints PASS/FAIL per check.
#
# Usage: bash scripts/smoke-dispatch.sh
#    or: npm run smoke:dispatch

set -u

fail=0
ok()  { echo "  ✓ $*"; }
err() { echo "  ✗ $*"; fail=$((fail + 1)); }

cd "$(dirname "$0")/.."

echo "=== 1. Production URLs (one app + the GHL public site) ==="
# url|expected-http-code|label
checks=(
  "https://tmmt-ops.vercel.app/login|200|tmmt-ops /login"
  "https://tmmt-ops.vercel.app/forms/customer-intake|200|tmmt-ops /forms/customer-intake"
  "https://tmmt-ops.vercel.app|307|tmmt-ops root (anonymous → GHL public site)"
  "https://allinonemanagementsolutions.com|200|GHL public site root"
)
for entry in "${checks[@]}"; do
  url=${entry%%|*}; rest=${entry#*|}; expect=${rest%%|*}; label=${rest##*|}
  code=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 15 "$url" || echo "ERR")
  if [ "$code" = "$expect" ]; then ok "$label → $code"
  else err "$label → $code (expected $expect)"; fi
done

echo
echo "=== 2. Dispatch source files present on master ==="
required=(
  "src/app/(command)/dispatch/layout.tsx"
  "src/app/(command)/dispatch/page.tsx"
  "src/app/(command)/dispatch/actions.ts"
  "src/app/(command)/dispatch/_components/DispatchMap.tsx"
  "src/app/(command)/dispatch/_components/OverridePanel.tsx"
  "src/app/(command)/dispatch/_components/AddressAutocomplete.tsx"
  "src/app/(command)/dispatch/incident/new/page.tsx"
  "src/app/(command)/dispatch/incident/[id]/page.tsx"
  "src/app/(command)/dispatch/units/page.tsx"
  "src/app/(command)/dispatch/responders/page.tsx"
  "src/app/(command)/dispatch/me/page.tsx"
  "src/lib/dispatch-types.ts"
  "src/lib/dispatch-queries.ts"
  "src/lib/osm-geocode.ts"
  "src/lib/osm-cache.ts"
  "src/lib/captain-client.ts"
  "src/lib/notify-telegram.ts"
  "supabase/migrations/20260530120000_rescue_dispatch_core.sql"
  "e2e/dispatch-rls.spec.ts"
  "docs/DISPATCH-CORE.md"
)
for f in "${required[@]}"; do
  if [ -f "$f" ]; then ok "$f"
  else err "missing: $f"; fi
done

echo
echo "=== 3. Migration content sanity ==="
mig="supabase/migrations/20260530120000_rescue_dispatch_core.sql"
if [ -f "$mig" ]; then
  for marker in \
    "CREATE TABLE public.org_roles" \
    "CREATE TABLE public.incidents" \
    "CREATE TABLE public.units" \
    "CREATE TABLE public.unit_locations" \
    "CREATE TABLE public.incident_assignments" \
    "CREATE TABLE public.assignment_overrides" \
    "CREATE TABLE public.org_responder_links" \
    "FUNCTION public.find_best_unit" \
    "FUNCTION public.assign_unit" \
    "FUNCTION public.next_dsp_ref_code" \
    "FUNCTION public.is_org_dispatcher" \
    "VIEW public.incident_assignments_v" \
    "ENABLE ROW LEVEL SECURITY"; do
    if grep -q "$marker" "$mig"; then ok "migration: $marker"
    else err "migration missing: $marker"; fi
  done
else
  err "migration file not found"
fi

echo
echo "=== 4. Map library is Leaflet (zero API keys) ==="
if grep -q '"leaflet":' package.json && grep -q '"react-leaflet":' package.json; then
  ok "package.json has leaflet + react-leaflet"
else
  err "package.json missing leaflet deps"
fi
if grep -q '"mapbox' package.json; then err "package.json still has mapbox dep residue"
else ok "no mapbox dep residue"; fi

echo
echo "=== 5. Public site (GHL) sanity ==="
bytes=$(curl -sS -L --max-time 15 https://allinonemanagementsolutions.com/ 2>/dev/null | wc -c | tr -d ' ')
if [ "${bytes:-0}" -gt 10000 ]; then ok "GHL public site renders ($bytes bytes)"
else err "GHL public site looks empty (${bytes:-0} bytes)"; fi

echo
echo "=== 6. Retired static landing kept for reference at AIXMOS/public/ ==="
for f in AIXMOS/public/index.html AIXMOS/public/apply.html AIXMOS/public/operator.html AIXMOS/public/thankyou.html AIXMOS/public/ghl-config.js; do
  if [ -f "$f" ]; then ok "$f"
  else err "missing: $f"; fi
done

echo
echo "=== 7. Local build sanity (TypeScript compiles) ==="
# Filter .next/ generated artifacts — those are regenerated by next dev/build
# and can carry stale route-validator types between runs.
if command -v npx >/dev/null; then
  real_errors=$(npx --no-install tsc --noEmit 2>&1 | grep "error TS" | grep -v "^\.next/" | head -10)
  if [ -n "$real_errors" ]; then
    err "tsc reports real errors:"
    echo "$real_errors" | sed 's/^/      /'
  else
    ok "tsc --noEmit clean (.next/ generated errors filtered)"
  fi
else
  err "npx not available — skipping tsc check"
fi

echo
if [ $fail -eq 0 ]; then
  echo "✅ ALL CHECKS PASSED"
  exit 0
else
  echo "❌ $fail check(s) failed"
  exit 1
fi
