#!/usr/bin/env bash
# ============================================================
# TAILSCALE MESH INVITE — Generate an invite for a new operator
# Run from Muhammad Taha's carry Mac.
# Requires: tailscale + owner access
# ============================================================
set -uo pipefail
G=$'\e[32m'; Y=$'\e[33m'; BD=$'\e[1m'; CY=$'\e[36m'; X=$'\e[0m'

ok()   { printf '%s  ✓ %s%s\n' "$G" "$*" "$X"; }
warn() { printf '%s  ⚠ %s%s\n' "$Y" "$*" "$X"; }
say()  { printf '\n%s%s%s\n' "$BD" "$*" "$X"; }

say "TAILSCALE MESH INVITE — AIXMOS Network"
echo "  This generates an auth key to add a new operator to your Tailscale mesh."
echo "  The key expires in 24 hours. One machine per key."
echo
read -p "  Operator name (e.g. umar): " OP_NAME
read -p "  Tag for this node [operator]: " OP_TAG
OP_TAG="${OP_TAG:-operator}"

echo
say "Tailscale options:"
echo "  [1] Open Tailscale Admin → create key manually (recommended)"
echo "  [2] Use tailscale CLI (requires admin API key)"
read -p "  Choice [1]: " CHOICE
CHOICE="${CHOICE:-1}"

if [[ "$CHOICE" == "1" ]]; then
  say "Open this URL on your phone or Mac to create a reusable auth key:"
  echo
  printf '  %s%shttps://login.tailscale.com/admin/settings/keys%s\n' "$CY$BD" "" "$X"
  echo
  echo "  Settings:"
  echo "  ✓ Check 'Reusable' = NO (one-time)"
  echo "  ✓ Check 'Ephemeral' = NO (persistent node)"
  echo "  ✓ Expiry = 24 hours"
  echo "  ✓ Tags = tag:$OP_TAG"
  echo
  read -p "  Paste the generated key here (starts with tskey-auth-): " TS_KEY
  echo
  if [[ -n "$TS_KEY" ]]; then
    # Write key to a temp file for Umar
    KEY_FILE="$HOME/Desktop/umar-tailscale-key-$(date +%Y%m%d).txt"
    cat > "$KEY_FILE" << KEY
UMAR TAILSCALE MESH KEY — $(date)
Generated by: Muhammad Taha / AIXMOS

On Umar's machine, run:
  sudo tailscale up --auth-key=$TS_KEY --hostname=red-hood-umar

This key expires in 24 hours. Do not share.
After joining, Muhammad Taha will see 'red-hood-umar' in the mesh.

Umar's tailnet will be scoped to credit-guidance tools only.
KEY
    chmod 600 "$KEY_FILE"
    ok "Key package saved to Desktop: umar-tailscale-key-$(date +%Y%m%d).txt"
    warn "AirDrop this file to Umar, then delete it from your Desktop."
    echo
    echo "  Command for Umar to run on his machine:"
    printf '  %s sudo tailscale up --auth-key=%s --hostname=red-hood-umar%s\n' "$CY" "$TS_KEY" "$X"
  fi
fi

say "Current mesh roster:"
tailscale status 2>/dev/null | head -15 || warn "tailscale not running"
