// AUTO-GENERATED by scripts/brand-sync.mjs — DO NOT EDIT BY HAND.
// Source of truth: config/platform/tenants/*.json
// Regenerate with: npm run brand:sync
//
// This module is intentionally free of node:fs and React imports so the Edge
// middleware and client components can share one brand map with the server.

export type BrandMode = "dark" | "light";

export type BrandTheme = {
  readonly mode: BrandMode;
  readonly primary: string;
  readonly accent: string;
  readonly background: string;
  readonly foreground: string;
  readonly logoPath: string;
  readonly markPath: string;
  readonly faviconPath: string;
};

export type TenantBrand = {
  readonly id: string;
  readonly slug: string;
  readonly aliases: readonly string[];
  readonly displayName: string;
  readonly legalName: string;
  readonly tagline: string;
  readonly initials: string;
  readonly licenseTier: string;
  readonly hasCustomLogo: boolean;
  readonly theme: BrandTheme;
  readonly domains: { readonly marketing?: string; readonly app?: string };
};

export const TENANTS: Record<string, TenantBrand> = {
  "aixmos_credit": {
    id: "aixmos-credit",
    slug: "aixmos_credit",
    aliases: ["aixmos-credit","credit","moe-legacy","moe_legacy"],
    displayName: "AIXMOS Credit",
    legalName: "AIXMOS Credit",
    tagline: "The go-to for getting funding-ready and funded",
    initials: "AC",
    licenseTier: "tenant",
    hasCustomLogo: false,
    theme: {
      mode: "dark",
      primary: "#34d399",
      accent: "#059669",
      background: "#0a0a0a",
      foreground: "#ffffff",
      logoPath: "/brands/aixmos-credit/logo.svg",
      markPath: "/brands/aixmos-credit/mark.svg",
      faviconPath: "/brands/aixmos-credit/favicon.svg",
    },
    domains: { marketing: "credit.aixmos.internal", app: "credit.aixmos.internal" },
  },
  "aixmos": {
    id: "aixmos",
    slug: "aixmos",
    aliases: ["aixmos537"],
    displayName: "AIXMOS",
    legalName: "All In One Management Solutions LLC",
    tagline: "The AI engine — agents that answer, follow up, and close 24/7",
    initials: "AI",
    licenseTier: "platform",
    hasCustomLogo: false,
    theme: {
      mode: "dark",
      primary: "#7fffd4",
      accent: "#6366f1",
      background: "#0a0a0a",
      foreground: "#ffffff",
      logoPath: "/brands/aixmos/logo.svg",
      markPath: "/brands/aixmos/mark.svg",
      faviconPath: "/brands/aixmos/favicon.svg",
    },
    domains: { marketing: "aixmos.com", app: "allinonemanagementsolutions.com" },
  },
  "tmmt_property": {
    id: "tmmt",
    slug: "tmmt_property",
    aliases: ["tmmt","tmmt-rentals","tmmt_property"],
    displayName: "TMMT",
    legalName: "TMMT Rentals",
    tagline: "The car rental agency that teaches you to run your own fleet",
    initials: "TM",
    licenseTier: "tenant",
    hasCustomLogo: false,
    theme: {
      mode: "dark",
      primary: "#a78bfa",
      accent: "#7c3aed",
      background: "#0a0a0a",
      foreground: "#ffffff",
      logoPath: "/brands/tmmt/logo.svg",
      markPath: "/brands/tmmt/mark.svg",
      faviconPath: "/brands/tmmt/favicon.svg",
    },
    domains: { marketing: "tmmtrentals.com", app: "tmmt-ops.vercel.app" },
  },
};

/** alias -> canonical slug */
export const TENANT_ALIASES: Record<string, string> = {
  "aixmos-credit": "aixmos_credit",
  "credit": "aixmos_credit",
  "moe-legacy": "aixmos_credit",
  "moe_legacy": "aixmos_credit",
  "aixmos537": "aixmos",
  "tmmt": "tmmt_property",
  "tmmt-rentals": "tmmt_property"
};

/** hostname (no port, lowercase) -> canonical slug */
export const TENANT_HOSTS: Record<string, string> = {
  "credit.aixmos.internal": "aixmos_credit",
  "aixmos.com": "aixmos",
  "allinonemanagementsolutions.com": "aixmos",
  "tmmtrentals.com": "tmmt_property",
  "tmmt-ops.vercel.app": "tmmt_property"
};

/** Platform-tier tenant — the brand used when nothing else resolves. */
export const DEFAULT_TENANT_SLUG = "aixmos";

export const TENANT_SLUGS: readonly string[] = Object.keys(TENANTS);
